name: Crystal CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v6
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
